spring:
  application:
    name: whataplabs-task-product

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9090

logging.level:
  com.whataplabs.task.product: debug
  org.hibernate.SQL: debug            # SQL ?? ?????.
  org.hibernate.type: trace           # ??? ????? ??? ??? ?????.
#  org.hibernate.orm.jdbc.bind: trace
